spring:
  application:
    name: bot
  datasource:
    url: jdbc:postgresql://localhost:5434/scrapper
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  rabbitmq:
    host: ${RABBIT_HOST}
    username: guest
    password: guest
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false

rabbit:
  queue: scrapper-queue
  exchange: scrapper-exchange

springdoc:
  swagger-ui:
    path: /swagger-ui

app:
  test: test
  token: ${BOT_TOKEN}

client:
  scrapperBaseUrl: ${SCRAPPER_URL}

management:
    metrics:
        tags:
            application: ${spring.application.name}
    server:
        port: 8090
    endpoints:
        web:
            base-path: /
            path-mapping:
                prometheus: /metrics
            exposure:
                include: "*"
        enabled-by-default: false

    endpoint:
        info:
            enabled: true
        health:
            enabled: true
        metrics:
            enabled: true
        prometheus:
            enabled: true
    prometheus:
        metrics:
            export:
                enabled: true
