spring:
  application:
    name: bot
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  rabbitmq:
    host: ${RABBIT_HOST}
    username: guest
    password: guest
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false

rabbit:
  queue: scrapper-queue
  exchange: scrapper-exchange

springdoc:
  swagger-ui:
    path: /swagger-ui

app:
  test: test
  token: ${BOT_TOKEN}

client:
  scrapperBaseUrl: ${SCRAPPER_URL}