name: scrapper CI/CD

on:
  push:
    paths:
      - 'scrapper/**'
      - 'build.gradle'
      - 'settings.gradle'
      - '.github/workflows/scrapper.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scrapper_app

jobs:
  build:
    needs: []
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build scrapper module with Gradle
        run: ./gradlew :scrapper:build

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build Docker image
        run: docker build -f ./scrapper/Dockerfile -t ${{ env.REGISTRY}}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY}}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest

  checkstyle:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up JDK 21
            uses: actions/setup-java@v3
            with:
                java-version: '21'
                distribution: 'temurin'

          - name: Cache Gradle dependencies
            uses: actions/cache@v4
            with:
              path: |
                  ~/.gradle/caches
                  ~/.gradle/wrapper
              key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
              restore-keys: |
                  ${{ runner.os }}-gradle-

          - name: Run Checkstyle
            run: ./gradlew :scrapper:checkstyleMain

          - name: Upload Checkstyle reports
            if: always()
            uses: actions/upload-artifact@v4
            with:
              name: checkstyle-reports
              path: |
                  **/build/reports/checkstyle/**
              retention-days: 7
